import { AnyUnit } from "./types";

export const UNIT_ALIASES: Record<string, AnyUnit> = {
  // Distance
  km: "km",
  kilometer: "km",
  kilometers: "km",
  kilometre: "km",
  kilometres: "km",
  m: "m",
  meter: "m",
  meters: "m",
  metre: "m",
  metres: "m",
  cm: "cm",
  centimeter: "cm",
  centimeters: "cm",
  centimetre: "cm",
  centimetres: "cm",
  mm: "mm",
  millimeter: "mm",
  millimeters: "mm",
  millimetre: "mm",
  millimetres: "mm",
  mi: "mi",
  mile: "mi",
  miles: "mi",
  ft: "ft",
  foot: "ft",
  feet: "ft",
  in: "in",
  inch: "in",
  inches: "in",
  yd: "yd",
  yard: "yd",
  yards: "yd",

  // Weight
  kg: "kg",
  kilogram: "kg",
  kilograms: "kg",
  g: "g",
  gram: "g",
  grams: "g",
  mg: "mg",
  milligram: "mg",
  milligrams: "mg",
  lb: "lb",
  lbs: "lb",
  pound: "lb",
  pounds: "lb",
  oz: "oz",
  ounce: "oz",
  ounces: "oz",
  t: "t",
  ton: "t",
  tons: "t",
  tonne: "t",
  tonnes: "t",
  "metric ton": "t",
  "metric tons": "t",

  // Area
  m2: "m2",
  sqm: "m2",
  "square meter": "m2",
  "square meters": "m2",
  "square metre": "m2",
  "square metres": "m2",
  "meters squared": "m2",
  "metres squared": "m2",
  "square m": "m2",
  "m squared": "m2",
  km2: "km2",
  "square kilometer": "km2",
  "square kilometers": "km2",
  "square kilometre": "km2",
  "square kilometres": "km2",
  "kilometers squared": "km2",
  "kilometres squared": "km2",
  "square km": "km2",
  "km squared": "km2",
  cm2: "cm2",
  sqcm: "cm2",
  "square centimeter": "cm2",
  "square centimeters": "cm2",
  "square centimetre": "cm2",
  "square centimetres": "cm2",
  "centimeters squared": "cm2",
  "square cm": "cm2",
  "cm squared": "cm2",
  ft2: "ft2",
  sqft: "ft2",
  "square foot": "ft2",
  "square feet": "ft2",
  "feet squared": "ft2",
  "square ft": "ft2",
  "ft squared": "ft2",
  in2: "in2",
  sqin: "in2",
  "square inch": "in2",
  "square inches": "in2",
  "inches squared": "in2",
  "square in": "in2",
  "in squared": "in2",
  acres: "acres",
  acre: "acres",
  ha: "ha",
  hectare: "ha",
  hectares: "ha",

  // Volume
  l: "l",
  liter: "l",
  liters: "l",
  litre: "l",
  litres: "l",
  ml: "ml",
  milliliter: "ml",
  milliliters: "ml",
  millilitre: "ml",
  millilitres: "ml",
  gal: "gal",
  gallon: "gal",
  gallons: "gal",
  qt: "qt",
  quart: "qt",
  quarts: "qt",
  pt: "pt",
  pint: "pt",
  pints: "pt",
  floz: "floz",
  "fl oz": "floz",
  "fluid ounce": "floz",
  "fluid ounces": "floz",
  cup: "cup",
  cups: "cup",

  // Temperature
  c: "C",
  celsius: "C",
  "degrees celsius": "C",
  "degree celsius": "C",
  "degrees c": "C",
  f: "F",
  fahrenheit: "F",
  "degrees fahrenheit": "F",
  "degree fahrenheit": "F",
  "degrees f": "F",
  k: "K",
  kelvin: "K",

  // Duration
  ms: "ms",
  millisecond: "ms",
  milliseconds: "ms",
  s: "s",
  sec: "s",
  secs: "s",
  second: "s",
  seconds: "s",
  min: "min",
  mins: "min",
  minute: "min",
  minutes: "min",
  h: "h",
  hr: "h",
  hrs: "h",
  hour: "h",
  hours: "h",
  d: "d",
  day: "d",
  days: "d",
  wk: "wk",
  week: "wk",
  weeks: "wk",
  mo: "mo",
  month: "mo",
  months: "mo",
  yr: "yr",
  year: "yr",
  years: "yr",

  // Angle
  deg: "deg",
  degree: "deg",
  degrees: "deg",
  rad: "rad",
  radian: "rad",
  radians: "rad",
  grad: "grad",
  gradian: "grad",
  gradians: "grad",
  gon: "grad",
  turn: "turn",
  turns: "turn",
  revolution: "turn",
  revolutions: "turn",
  rev: "turn",

  // Energy
  j: "j",
  joule: "j",
  joules: "j",
  kj: "kj",
  kilojoule: "kj",
  kilojoules: "kj",
  cal: "cal",
  calorie: "cal",
  calories: "cal",
  kcal: "kcal",
  kilocalorie: "kcal",
  kilocalories: "kcal",
  wh: "wh",
  "watt hour": "wh",
  "watt hours": "wh",
  kwh: "kwh",
  "kilowatt hour": "kwh",
  "kilowatt hours": "kwh",
  ev: "ev",
  electronvolt: "ev",
  electronvolts: "ev",
  btu: "btu",
  "british thermal unit": "btu",
  "british thermal units": "btu",

  // Frequency
  hz: "hz",
  hertz: "hz",
  khz: "khz",
  kilohertz: "khz",
  mhz: "mhz",
  megahertz: "mhz",
  ghz: "ghz",
  gigahertz: "ghz",
  rpm: "rpm",
  "revolutions per minute": "rpm",

  // Power
  w: "w",
  watt: "w",
  watts: "w",
  kw: "kw",
  kilowatt: "kw",
  kilowatts: "kw",
  mw: "mw",
  megawatt: "mw",
  megawatts: "mw",
  hp: "hp",
  horsepower: "hp",
  "btu/hr": "btuhr",
  "btu/h": "btuhr",
  "btu per hour": "btuhr",

  // Speed
  "m/s": "ms",
  "meter per second": "ms",
  "meters per second": "ms",
  "metre per second": "ms",
  "metres per second": "ms",
  mps: "ms",
  "km/h": "kmh",
  kph: "kmh",
  "kilometer per hour": "kmh",
  "kilometers per hour": "kmh",
  "kilometre per hour": "kmh",
  "kilometres per hour": "kmh",
  kmph: "kmh",
  mph: "mph",
  "mile per hour": "mph",
  "miles per hour": "mph",
  knot: "knot",
  knots: "knot",
  kt: "knot",
  "ft/s": "fts",
  fps: "fts",
  "foot per second": "fts",
  "feet per second": "fts",
};

export function normalizeUnit(raw: string): AnyUnit | null {
  return UNIT_ALIASES[raw.toLowerCase().trim()] ?? null;
}

export const DISTANCE_UNITS = new Set<AnyUnit>(["km", "m", "cm", "mm", "mi", "ft", "in", "yd"]);
export const WEIGHT_UNITS = new Set<AnyUnit>(["kg", "g", "mg", "lb", "oz", "t"]);
export const AREA_UNITS = new Set<AnyUnit>(["m2", "km2", "cm2", "ft2", "in2", "acres", "ha"]);
export const VOLUME_UNITS = new Set<AnyUnit>(["l", "ml", "gal", "qt", "pt", "floz", "cup"]);
export const TEMP_UNITS = new Set<AnyUnit>(["C", "F", "K"]);
export const DURATION_UNITS = new Set<AnyUnit>(["ms", "s", "min", "h", "d", "wk", "mo", "yr"]);
export const ANGLE_UNITS = new Set<AnyUnit>(["deg", "rad", "grad", "turn"]);
export const ENERGY_UNITS = new Set<AnyUnit>(["j", "kj", "cal", "kcal", "wh", "kwh", "ev", "btu"]);
export const FREQUENCY_UNITS = new Set<AnyUnit>(["hz", "khz", "mhz", "ghz", "rpm"]);
export const POWER_UNITS = new Set<AnyUnit>(["w", "kw", "mw", "hp", "btuhr"]);
export const SPEED_UNITS = new Set<AnyUnit>(["ms", "kmh", "mph", "knot", "fts"]);
